# Generated by Django 4.0.5 on 2022-06-21 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='students',
            fields=[
                ('id', models.CharField(auto_created=False, primary_key=True, serialize=False, verbose_name='ID',max_length=4)),
                ('gender', models.CharField(max_length=10)),
                ('ageGroup', models.CharField(max_length=40)),
                ('year', models.IntegerField()),
                ('area', models.CharField(max_length=40)),
            ],
        ),
    ]
