# Generated by Django 4.0.5 on 2022-06-22 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentLifeApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='ageGroup',
            field=models.CharField(choices=[('Younger than 17 years', 'a'), ('17 to 20 years', 'b'), ('21 a 23 years', 'c'), ('Older than 23 years', 'd')], max_length=40),
        ),
        migrations.AlterField(
            model_name='students',
            name='id',
            field=models.CharField(primary_key=True, serialize=False, max_length=4),
        ),
    ]
